version: '2'
services:
        web:
                image: responsi165610105
                volumes:
                    - ./src:/usr/share/nginx/html
                ports:
                     - "80:80"
